plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
#  - algoliasearch-jekyll

staticurl: https://plot.ly/gh-pages/documentation/static/

#stylesheet: https://s3-us-west-1.amazonaws.com/plotly-tutorials/assets/web-excel/css/main.css
stylesheet: /styles/main.css

title: Plotly Help Center

exclude:
  - .sass-cache
  - scss
  - node_modules
  - gulpfile.js
  - vendor

#
#algolia:
#  application_id:      'UFNFY0UTNN'
#  index_name:          'help.plot.ly'
#  search_only_api_key: '58a3e4e581f186e87bd219d92431cc42'
